server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://10.1.1.240:3306/z_t2?useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: tcjk@mysql
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
check-user-scopes: false
